---
- name: Install everything
  hosts: all
  any_errors_fatal: true
  become: true
  tasks:
    - block:
        - name: Print all the packages to be installed
          ansible.builtin.debug:
            msg: "{{ pkg[ansible_host] }}"

        - name: Ensure apt packages are installed
          ansible.builtin.apt:
            pkg: "{{ pkg[ansible_host]['apt'] }}"
            state: present

        - name: Ensure pip is installed
          ansible.builtin.apt:
            name: python3-pip
            state: present

        - name: Ensure pip packages are installed
          ansible.builtin.pip:
            name: "{{ pkg[ansible_host]['pip'] | join(' ') }}"
            state: present
          when: pkg[ansible_host]['pip'] | length > 0

