Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 1024
  end

  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "generic/ubuntu2004"
    vm1.vm.network :private_network, :ip => "192.168.10.10"
  end

  config.vm.define :vm2 do |vm2|
    vm2.vm.box = "generic/ubuntu2004"
    vm2.vm.network :private_network, :ip => "192.168.10.11"
  end

  config.vm.define :vm3 do |vm3|
    vm3.vm.box = "generic/ubuntu2004"
    vm3.vm.network :private_network, :ip => "192.168.10.12"
  end
end
