---
- name: Ensure pip is installed
  ansible.builtin.apt:
     name: python3-pip
     state: present

- name: "Print all the pip packages to be {{ pkg_state }}"
  ansible.builtin.debug:
    msg: "{{ host_packages[ansible_host]['pip'] }}"

- name: "Ensure pip packages are {{ pkg_state }}"
  ansible.builtin.pip:
    name: "{{ host_packages[ansible_host]['pip'] | join(' ') }}"
    state: "{{ pkg_state }}"
  when: host_packages[ansible_host]['pip'] | length > 0
