---
- name: Verify os family
  fail:
    msg: "Incompatible os family"
  when: ansible_os_family != "Debian"

# TODO: loop over package managers
- name: "Install all apt packages"
  import_tasks: pkg_apt.yml

- name: "Install all pip packages"
  import_tasks: pkg_pip.yml
