---
- name: Ensure pip is installed
  ansible.builtin.apt:
     name: python3-pip
     state: present
  become: true

- name: "Print all the pip packages to be {{ pkg_state }}"
  ansible.builtin.debug:
    msg: "{{ pkg['pip'] }}"

- name: "Ensure pip packages are {{ pkg_state }}"
  ansible.builtin.pip:
    name: "{{ pkg['pip'] | join(' ') }}"
    state: "{{ pkg_state }}"
  when: pkg['pip'] | length > 0
