---
- name: "Print all the apt packages to be {{ pkg_state }}"
  ansible.builtin.debug:
    msg: "{{ pkg['apt'] }}"

- name: "Ensure apt packages are {{ pkg_state }}"
  ansible.builtin.apt:
    pkg: "{{ pkg['apt'] }}"
    state: "{{ pkg_state }}"
    update_cache: yes
    cache_valid_time: 600
  become: true
